export const menus = [
  {
    label: 'descriptions',
    href: '/descriptions',
    code: '/descriptions',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'empty',
    href: '/empty',
    code: '/empty',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'jdata-viewer',
    href: '/jdata-viewer',
    code: '/jdata-viewer',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'remote-search',
    href: '/remote-search',
    code: '/remote-search',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'search-form',
    href: '/search-form',
    code: '/search-form',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'sticky-container',
    href: '/sticky-container',
    code: '/sticky-container',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'table',
    href: '/table',
    code: '/table',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'tabs',
    href: '/tabs',
    code: '/tabs',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'tarea-tag',
    href: '/tarea-tag',
    code: '/tarea-tag',
    closable: false,
    mode: 'router',
    icon: '',
  },
  {
    label: 'uploader',
    href: '/uploader',
    code: '/uploader',
    closable: false,
    mode: 'router',
    icon: '',
  },
]
