/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    YtoCEmpty: (typeof import('@yto/custom/es/components/cempty/index.mjs'))['YtoCEmpty']
    YtoCJsonViewer: (typeof import('@yto/custom/es/components/cjson-viewer/index.mjs'))['YtoCJsonViewer']
    YtoDescriptions: (typeof import('@yto/custom/es/components/descriptions/index.mjs'))['YtoDescriptions']
    YtoEmpty: (typeof import('@yto/custom/es/components/empty/index.mjs'))['YtoEmpty']
    YtoJdataViewer: (typeof import('@yto/custom/es/components/jdata-viewer/index.mjs'))['YtoJdataViewer']
    YtoLayoutHeader: (typeof import('@yto/custom/es/components/layout-header/index.mjs'))['YtoLayoutHeader']
    YtoLayoutMenu: (typeof import('@yto/custom/es/components/layout-menu/index.mjs'))['YtoLayoutMenu']
    YtoLayoutRouter: (typeof import('@yto/custom/es/components/layout-router/index.mjs'))['YtoLayoutRouter']
    YtoRemoteSearch: (typeof import('@yto/custom/es/components/remote-search/index.mjs'))['YtoRemoteSearch']
    YtoSearchForm: (typeof import('@yto/custom/es/components/search-form/index.mjs'))['YtoSearchForm']
    YtoStickyContainer: (typeof import('@yto/custom/es/components/sticky-container/index.mjs'))['YtoStickyContainer']
    YtoTable: (typeof import('@yto/custom/es/components/table/index.mjs'))['YtoTable']
    YtoTabs: (typeof import('@yto/custom/es/components/tabs/index.mjs'))['YtoTabs']
    YtoTareaTag: (typeof import('@yto/custom/es/components/tarea-tag/index.mjs'))['YtoTareaTag']
    YtoUploader: (typeof import('@yto/custom/es/components/uploader/index.mjs'))['YtoUploader']
  }
}
