/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    YtoAdaptionContainer: (typeof import('@yto/custom/es/components/adaption-container/index.mjs'))['YtoAdaptionContainer']
    YtoCustomFieldConfig: (typeof import('@yto/custom/es/components/custom-field-config/index.mjs'))['YtoCustomFieldConfig']
    YtoEmpty: (typeof import('@yto/custom/es/components/empty/index.mjs'))['YtoEmpty']
    YtoForm: (typeof import('@yto/custom/es/components/form/index.mjs'))['YtoForm']
    YtoFormItems: (typeof import('@yto/custom/es/components/form-items/index.mjs'))['YtoFormItems']
    YtoLayoutHeader: (typeof import('@yto/custom/es/components/layout-header/index.mjs'))['YtoLayoutHeader']
    YtoLayoutMenu: (typeof import('@yto/custom/es/components/layout-menu/index.mjs'))['YtoLayoutMenu']
    YtoLayoutRouter: (typeof import('@yto/custom/es/components/layout-router/index.mjs'))['YtoLayoutRouter']
    YtoSearchForm: (typeof import('@yto/custom/es/components/search-form/index.mjs'))['YtoSearchForm']
    YtoTable: (typeof import('@yto/custom/es/components/table/index.mjs'))['YtoTable']
  }
}
