/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YtoAdaptionContainer: typeof import('@yto/custom/es/components/adaption-container/index.mjs')['YtoAdaptionContainer']
    YtoCustomFieldConfig: typeof import('@yto/custom/es/components/custom-field-config/index.mjs')['YtoCustomFieldConfig']
    YtoCustomFieldContainer: typeof import('@yto/custom/es/components/custom-field-container/index.mjs')['YtoCustomFieldContainer']
    YtoDatePicker: typeof import('@yto/custom/es/components/date-picker/index.mjs')['YtoDatePicker']
    YtoEchart: typeof import('@yto/custom/es/components/echart/index.mjs')['YtoEchart']
    YtoEllipsisTag: typeof import('@yto/custom/es/components/ellipsis-tag/index.mjs')['YtoEllipsisTag']
    YtoEmpty: typeof import('@yto/custom/es/components/empty/index.mjs')['YtoEmpty']
    YtoJdataViewer: typeof import('@yto/custom/es/components/jdata-viewer/index.mjs')['YtoJdataViewer']
    YtoRadio: typeof import('@yto/custom/es/components/radio/index.mjs')['YtoRadio']
    YtoRemoteSearch: typeof import('@yto/custom/es/components/remote-search/index.mjs')['YtoRemoteSearch']
    YtoSearchForm: typeof import('@yto/custom/es/components/search-form/index.mjs')['YtoSearchForm']
    YtoTable: typeof import('@yto/custom/es/components/table/index.mjs')['YtoTable']
    YtoTableEditor: typeof import('@yto/custom/es/components/table-editor/index.mjs')['YtoTableEditor']
    YtoTabs: typeof import('@yto/custom/es/components/tabs/index.mjs')['YtoTabs']
    YtoTareaTag: typeof import('@yto/custom/es/components/tarea-tag/index.mjs')['YtoTareaTag']
    YtoTextEllipsis: typeof import('@yto/custom/es/components/text-ellipsis/index.mjs')['YtoTextEllipsis']
    YtoTimeLine: typeof import('@yto/custom/es/components/time-line/index.mjs')['YtoTimeLine']
    YtoUploader: typeof import('@yto/custom/es/components/uploader/index.mjs')['YtoUploader']
    YtoUserSearch: typeof import('@yto/custom/es/components/user-search/index.mjs')['YtoUserSearch']
    YtoWaterMark: typeof import('@yto/custom/es/components/water-mark/index.mjs')['YtoWaterMark']
  }
}
