/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YtoDescriptions: typeof import('@yto/custom/es/components/descriptions/index.mjs')['YtoDescriptions']
    YtoDialog: typeof import('@yto/custom/es/components/dialog/index.mjs')['YtoDialog']
    YtoEmpty: typeof import('@yto/custom/es/components/empty/index.mjs')['YtoEmpty']
    YtoRemoteSearch: typeof import('@yto/custom/es/components/remote-search/index.mjs')['YtoRemoteSearch']
    YtoSearchForm: typeof import('@yto/custom/es/components/search-form/index.mjs')['YtoSearchForm']
    YtoStickyContainer: typeof import('@yto/custom/es/components/sticky-container/index.mjs')['YtoStickyContainer']
    YtoTextEllipsis: typeof import('@yto/custom/es/components/text-ellipsis/index.mjs')['YtoTextEllipsis']
    YtoUserSearch: typeof import('@yto/custom/es/components/user-search/index.mjs')['YtoUserSearch']
  }
}
